"""first migrate

Revision ID: c8c8869acba3
Revises: 
Create Date: 2021-08-10 21:59:33.937634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c8869acba3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_offs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_offs_id'), 'day_offs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('account', sa.String(length=30), nullable=True),
    sa.Column('passwd', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('department', sa.String(length=20), nullable=True),
    sa.Column('manager', sa.Boolean(), nullable=True),
    sa.Column('hr', sa.Boolean(), nullable=True),
    sa.Column('on_job', sa.Date(), nullable=True),
    sa.Column('off_job', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account'), 'users', ['account'], unique=True)
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('base_salarys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('self_percent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_salarys_id'), 'base_salarys', ['id'], unique=False)
    op.create_table('dailys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('on', sa.Time(), nullable=True),
    sa.Column('off', sa.Time(), nullable=True),
    sa.Column('on_fix', sa.Time(), nullable=True),
    sa.Column('off_fix', sa.Time(), nullable=True),
    sa.Column('fix_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailys_id'), 'dailys', ['id'], unique=False)
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('check', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaves_id'), 'leaves', ['id'], unique=False)
    op.create_table('overtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('start', sa.Time(), nullable=True),
    sa.Column('end', sa.Time(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('check', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overtimes_id'), 'overtimes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_overtimes_id'), table_name='overtimes')
    op.drop_table('overtimes')
    op.drop_index(op.f('ix_leaves_id'), table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_dailys_id'), table_name='dailys')
    op.drop_table('dailys')
    op.drop_index(op.f('ix_base_salarys_id'), table_name='base_salarys')
    op.drop_table('base_salarys')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.drop_index(op.f('ix_users_account'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_day_offs_id'), table_name='day_offs')
    op.drop_table('day_offs')
    # ### end Alembic commands ###
